### ISSUE TITLE
Opbrengsten View

### ISSUE THREAD

**Issue by woesterudolf** [Nhaaksema/ParkeerGarage#26]

**Comment by Nhaaksema** [comment]
Maak een extra view voor de applicatie, hierin moet informatie in tekstvorm worden gepresenteerd. In deze view moet belangrijke management informatie worden weergegeven. Je moet in deze view de opbrengst van de dag weergeven en de verwachtte opbrengst van de klanten die nog in de garage aanwezig zijn maar nog niet hebben betaald
