### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by Nhaaksema** [Nhaaksema/ParkeerGarage#6]
Vergelijk de implementatie van MVC in het MVCDynamicModelThread project met die in het MVCDynamicModelThreadGeneralized project en vergelijk dit laatste project ook met het Life project. Wat zijn de overeenkomsten en wat zijn de verschillen?
Beschrijf je bevindingen in het rapport in “Hoofdstuk 3 – MVC gebruiken”. Beschrijf ook hoe je in het project parkeer-garage dezelfde MVC structuur kunt krijgen als in het Life project. Maak een ontwerp dat de nieuwe structuur van het programma weergeeft. Laat dit nieuwe ontwerp door je docent controleren voordat je de veranderingen implementeert.

**Comment by teletobbie** [comment]
De nieuwe (concept) project structuur van ParkeerSimulator. De structuur zal bestaan uit verschillende packages. 

parkeersimulator.main
    simulator.java
parkeersimulator.runner
    run.java
parkeersimulator.view
    simulatorview.java
parkeersimulator.model
    car.java
    location.java
    parkPassCar.java
parkeersimulator.logic
    carQueue.java
    adHocCar.java
parkeersimulator.controller
    *hier zou naar mijn mening de simulator.java moeten worden opgehakt in verschillende controllers.*
