### ISSUE TITLE
Extra Views toevoegen

### ISSUE THREAD

**Issue by Nhaaksema** [Nhaaksema/ParkeerGarage#7]
Maak een extra view voor de applicatie, hierin moet informatie in tekstvorm worden gepresenteerd. In deze view moet belangrijke management informatie worden weergegeven. Je moet in deze view de opbrengst van de dag weergeven en de verwachtte opbrengst van de klanten die nog in de garage aanwezig zijn maar nog niet hebben betaald. Maak gebruik van de AbstractView structuur die je in het Life project kunt vinden.

Implementeer nog drie andere views, je kunt bijvoorbeeld de manier waarop de huidige informatie wordt weergegeven veranderen (i.e. histogrammen of lijn grafieken). Ook moet je de informatie over de queues weergeven. Zorg er voor dat je in alle views duidelijk kunt zien welk soort auto’s weeggeven worden.

1. Tekstvorm view

2. Lijngrafieken

3.

**Comment by woesterudolf** [comment]
Dit kan hier handig voor zijn

https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html

**Comment by woesterudolf** [comment]
https://docs.oracle.com/javase/tutorial/2d/images/saveimage.html
https://www.mkyong.com/java/how-to-export-data-to-csv-file-java/
